version: '3'
services:
# 中间件
    # 网关
    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - 80:80
        environment:
            TZ: Asia/Shanghai
        volumes:
            - $PWD/conf/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
            - $PWD/conf/nginx/conf.d:/etc/nginx/conf.d
            - $PWD/data/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
            - $PWD/log/nginx:/var/log/nginx #日志文件挂载
        restart: unless-stopped
    # 关系型数据库
    pgsql:
        image: postgres:13
        container_name: pgsql
        ports:
            - 5432:5432
        environment:
            # POSTGRES_PASSWORD: 123456
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
        volumes:
            - $PWD/conf/pgsql/:/etc/postgresql/ #配置文件挂载
            - $PWD/conf/pgsql/secrets:/run/secrets
            - $PWD/data/pgsql:/var/lib/postgresql/data #数据文件挂载
        restart: unless-stopped
    # 内存数据库
    redis:
        image: redis:6
        container_name: redis-server
        ports:
            - 6379:6379
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        volumes:
            - $PWD/conf/redis/:/usr/local/etc/redis/
            - $PWD/data/redis:/data #数据文件挂载
        restart: unless-stopped
    # 文档数据库
    mongo:
        image: mongo:4
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - $PWD/conf/mongo/secrets/:/run/secrets/
            - $PWD/data/mongo/:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root
            TZ: Asia/Shanghai
        # restart: unless-stopped
    # OSS对象存储
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - 9000:9000
        volumes:
            - $PWD/data/minio/:/data/
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data
        # restart: unless-stopped
    # 服务发现
    nacos:
        image: nacos/nacos-server:2.0.2
        container_name: nacos-server
        ports:
            - 8848:8848
        environment:
            MODE: standalone
        restart: unless-stopped
    # 日志采集
    logstash:
        image: logstash:7.13.0
        container_name: logstash
        volumes:
            - $PWD/conf/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        # restart: unless-stopped
    # 消息队列
    pulsar:
        image: apachepulsar/pulsar:2.8.0
        container_name: pulsar
        ports:
            - 6650:6650
            - 19002:8080
        volumes:
            - $PWD/data/pulsar/:/pulsar/data/
        # restart: unless-stopped
# 运维工具
    # docker可视化管理
    portainer:
        image: portainer/portainer-ce:alpine
        container_name: portainer
        ports:
            - 19000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/data/portainer/:/data/
        restart: always
    # 服务监控系统
    prometheus:
        image: prom/prometheus:v2.28.0
        container_name: prometheus
        # restart: unless-stopped
    # 可视化分析工具
    grafana:
        image: grafana/grafana:8.0.6
        container_name: grafana
        ports:
            - 19001:3000
        # restart: unless-stopped
# 应用
